services:
  - type: web
    name: smartqr-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/SmartQr-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: RENDER_URL
        value: https://smartqr-backend.onrender.com